name: React Todo CI/CD

on:
  push:
    branches:
      - main
      - feature

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
